services:
  - type: web
    name: reachinbox-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install --legacy-peer-deps && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 9000
      - key: DATABASE_URL
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: ELASTICSEARCH_URL
        value: http://127.0.0.1:9200
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: FRONTEND_URL
        sync: false
